# Generated by Django 5.2.9 on 2026-09-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_doublespair'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('participant_type', models.CharField(choices=[('individual', 'Individual'), ('doubles', 'Doubles'), ('team', 'Team')], max_length=20, verbose_name='Participant type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tournament', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_of_sets', models.PositiveSmallIntegerField(choices=[(3, 'Best of 3'), (5, 'Best of 5'), (7, 'Best of 7')], default=5, verbose_name='Best of sets')),
                ('points_per_set', models.PositiveSmallIntegerField(default=11, verbose_name='Points per set')),
                ('win_by', models.PositiveSmallIntegerField(default=2, verbose_name='Win by')),
                ('deciding_set_points', models.PositiveSmallIntegerField(blank=True, help_text='Leave blank to use the same points as other sets.', null=True, verbose_name='Deciding set points')),
                ('cap_at', models.PositiveSmallIntegerField(blank=True, help_text="Optional hard cap on a set's winning score, regardless of win-by-N.", null=True, verbose_name='Hard cap')),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='tournaments.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('stage_format', models.CharField(choices=[('round_robin', 'Round robin'), ('knockout', 'Knockout')], max_length=20, verbose_name='Format')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournaments.competition')),
            ],
            options={
                'ordering': ['competition', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.stage')),
            ],
            options={
                'ordering': ['stage', 'order'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='tournaments.tournament'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('individual', 'Individual'), ('doubles', 'Doubles'), ('team', 'Team')], max_length=20, verbose_name='Type')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Display name')),
                ('seed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seed')),
                ('is_bye', models.BooleanField(default=False, verbose_name='BYE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.competition')),
                ('doubles_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournament_participations', to='players.doublespair')),
                ('individual_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournament_participations', to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournament_participations', to='teams.team')),
            ],
            options={
                'ordering': ['competition', 'seed', 'display_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('doubles_pair__isnull', True), ('individual_player__isnull', True), ('is_bye', True), ('team__isnull', True)), models.Q(('doubles_pair__isnull', True), ('individual_player__isnull', False), ('is_bye', False), ('participant_type', 'individual'), ('team__isnull', True)), models.Q(('doubles_pair__isnull', False), ('individual_player__isnull', True), ('is_bye', False), ('participant_type', 'doubles'), ('team__isnull', True)), models.Q(('doubles_pair__isnull', True), ('individual_player__isnull', True), ('is_bye', False), ('participant_type', 'team'), ('team__isnull', False)), _connector='OR'), name='participant_reference_matches_type'), models.UniqueConstraint(condition=models.Q(('seed__isnull', False)), fields=('competition', 'seed'), name='unique_seed_per_competition')],
            },
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('competition', 'order'), name='unique_stage_order_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('stage', 'name'), name='unique_group_name_per_stage'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_competition_name_per_tournament'),
        ),
    ]
