# Generated by Django 5.2.9 on 2026-09-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_participants', to='tournaments.group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='tournaments.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'participant'), name='unique_participant_per_group')],
            },
        ),
    ]
