# Generated by Django 5.2.9 on 2026-09-04 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_groupparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tournament_admin', 'Tournament Admin'), ('tournament_manager', 'Tournament Manager'), ('referee', 'Referee'), ('scorekeeper', 'Scorekeeper')], max_length=30, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tournament', 'role', 'user'],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'user', 'role'), name='unique_staff_role_per_tournament')],
            },
        ),
    ]
