# Generated by Django 5.2.9 on 2026-09-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
        ('tournaments', '0003_tournamentstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='ranking_category',
            field=models.ForeignKey(blank=True, help_text='If set, final placements in this competition can award points to this global ranking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='rankings.rankingcategory', verbose_name='Ranking category'),
        ),
        migrations.AddField(
            model_name='stage',
            name='qualifiers_per_group',
            field=models.PositiveIntegerField(blank=True, help_text="For a round-robin stage only: how many top finishers from each group advance to the competition's next (knockout) stage.", null=True, verbose_name='Qualifiers per group'),
        ),
    ]
