# Generated by Django 5.2.9 on 2026-09-06 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_elorating_eloratingevent'),
        ('tournaments', '0004_competition_ranking_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='ranking_category',
            field=models.ForeignKey(blank=True, help_text="Elo ratings update after every match, and final placements can award points, to this global ranking. Defaults to the shared 'Overall' category automatically — clear this to keep a specific competition (e.g. a casual friendly) out of the global ranking.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='rankings.rankingcategory', verbose_name='Ranking category'),
        ),
    ]
