# Generated by Django 5.2.9 on 2026-09-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_player_unique_player_mobile_number_and_more'),
        ('teams', '0001_initial'),
        ('tournaments', '0006_backfill_default_ranking_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_tie_slot',
            field=models.BooleanField(default=False, help_text="On-demand Individual participant standing in for one named player inside a Team competition's tie — not a real draw entrant of this competition.", verbose_name='Tie slot'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_tie_slot', True)), fields=('competition', 'individual_player'), name='unique_tie_slot_participant_per_player'),
        ),
    ]
