# Generated by Django 5.2.9 on 2026-09-09 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_participant_is_tie_slot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='registration_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants. Enforced for self-registration and for participants added by staff alike. Leave blank for no limit.', null=True, verbose_name='Registration capacity'),
        ),
        migrations.AddField(
            model_name='competition',
            name='registration_open',
            field=models.BooleanField(default=False, help_text='While on, any logged-in user with a player profile can register themselves for this competition.', verbose_name='Registration open'),
        ),
        migrations.AddField(
            model_name='stage',
            name='is_locked',
            field=models.BooleanField(default=False, help_text="Once locked, this stage's group assignments and bracket can't be changed until an administrator explicitly unlocks it (CLAUDE.md section 10: a locked draw must not be modified silently).", verbose_name='Locked'),
        ),
        migrations.CreateModel(
            name='TournamentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('participant_added_by_staff', 'Participant added by staff'), ('participant_removed_by_staff', 'Participant removed by staff'), ('groups_created', 'Groups created'), ('participant_moved', 'Participant moved between groups'), ('stage_locked', 'Stage locked'), ('stage_unlocked', 'Stage unlocked'), ('bracket_swapped', 'Bracket participants swapped')], max_length=40, verbose_name='Action')),
                ('message', models.CharField(max_length=300, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
