# Generated by Django 5.2.9 on 2026-09-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoublesPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_pairs_as_player_one', to='players.player')),
                ('player_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_pairs_as_player_two', to='players.player')),
            ],
            options={
                'ordering': ['player_one__last_name', 'player_two__last_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('player_one', models.F('player_two')), _negated=True), name='doubles_pair_distinct_players'), models.UniqueConstraint(fields=('player_one', 'player_two'), name='unique_doubles_pair')],
            },
        ),
    ]
