# Generated by Django 5.2.9 on 2026-09-07 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_doublespair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bale_chat_id',
            field=models.BigIntegerField(blank=True, editable=False, help_text='Set automatically once the player shares their phone number with the Bale bot.', null=True, unique=True, verbose_name='Bale chat ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='mobile_number',
            field=models.CharField(blank=True, help_text="Used to link this player's Bale chat for match notifications, e.g. 0912xxxxxxx.", max_length=15, verbose_name='Mobile number'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(condition=models.Q(('mobile_number', ''), _negated=True), fields=('mobile_number',), name='unique_player_mobile_number'),
        ),
    ]
