# Generated by Django 5.2.9 on 2026-09-07 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_bale_chat_id_player_mobile_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='unique_player_mobile_number',
        ),
        migrations.AlterField(
            model_name='player',
            name='mobile_number',
            field=models.CharField(help_text="Used to link this player's Bale chat for match notifications, e.g. 0912xxxxxxx.", max_length=15, unique=True, verbose_name='Mobile number'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('mobile_number', ''), _negated=True), name='player_mobile_number_required'),
        ),
    ]
