# Generated by Django 5.2.9 on 2026-09-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_doublespair'),
        ('tournaments', '0003_tournamentstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Ranking category',
                'verbose_name_plural': 'Ranking categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Points')),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Previous rank')),
                ('current_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Current rank')),
                ('tournaments_played', models.PositiveIntegerField(default=0, verbose_name='Tournaments played')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='players.player')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_rankings', to='rankings.rankingcategory')),
            ],
            options={
                'verbose_name': 'Player ranking',
                'ordering': ['category', '-points', 'player'],
                'indexes': [models.Index(fields=['category', 'current_rank'], name='rankings_pl_categor_4d7b55_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'category'), name='unique_ranking_per_player_and_category')],
            },
        ),
        migrations.CreateModel(
            name='RankingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.PositiveIntegerField(verbose_name='Placement')),
                ('points_awarded', models.PositiveIntegerField(verbose_name='Points awarded')),
                ('points_before', models.PositiveIntegerField(verbose_name='Points before')),
                ('points_after', models.PositiveIntegerField(verbose_name='Points after')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rankings.rankingcategory')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_events', to='tournaments.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_events', to='players.player')),
            ],
            options={
                'verbose_name': 'Ranking event',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('player', 'category', 'competition'), name='unique_ranking_event_per_player_and_competition')],
            },
        ),
        migrations.CreateModel(
            name='RankingPointsScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.PositiveIntegerField(verbose_name='Placement')),
                ('points', models.PositiveIntegerField(verbose_name='Points')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_scale', to='rankings.rankingcategory')),
            ],
            options={
                'verbose_name': 'Ranking points scale entry',
                'verbose_name_plural': 'Ranking points scale',
                'ordering': ['category', 'placement'],
                'constraints': [models.UniqueConstraint(fields=('category', 'placement'), name='unique_placement_per_category')],
            },
        ),
    ]
