# Generated by Django 5.2.9 on 2026-09-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_match_participant_a_alter_match_participant_b_and_more'),
        ('players', '0002_doublespair'),
        ('rankings', '0001_initial'),
        ('tournaments', '0004_competition_ranking_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EloRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1500.0, verbose_name='Rating')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='Matches played')),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Previous rank')),
                ('current_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Current rank')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_ratings', to='rankings.rankingcategory')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_ratings', to='players.player')),
            ],
            options={
                'verbose_name': 'Elo rating',
                'ordering': ['category', '-rating', 'player'],
                'indexes': [models.Index(fields=['category', 'current_rank'], name='rankings_el_categor_90beee_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'category'), name='unique_elo_rating_per_player_and_category')],
            },
        ),
        migrations.CreateModel(
            name='EloRatingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField(verbose_name='Won')),
                ('rating_before', models.FloatField(verbose_name='Rating before')),
                ('rating_after', models.FloatField(verbose_name='Rating after')),
                ('delta', models.FloatField(verbose_name='Delta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_events', to='rankings.rankingcategory')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_events', to='matches.match')),
                ('opponent_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.participant')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_events', to='players.player')),
            ],
            options={
                'verbose_name': 'Elo rating event',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('match', 'player'), name='unique_elo_event_per_match_and_player')],
            },
        ),
    ]
