#!/usr/bin/env python3
"""Refresh the local Bale documentation snapshot from docs.bale.ai.

Usage:
    python tools/bale/update_docs.py
    python tools/bale/update_docs.py --url https://docs.bale.ai/ --output .claude/skills/bale-bot-api/reference

The script intentionally stores a source snapshot plus compact navigation files.
It uses only the Python standard library by default. If BeautifulSoup is installed,
it uses it for better table extraction.
"""

from __future__ import annotations

import argparse
import html
import re
import sys
import urllib.request
from html.parser import HTMLParser
from pathlib import Path

DEFAULT_URL = "https://docs.bale.ai/"
DEFAULT_OUTPUT = Path(".claude/skills/bale-bot-api/reference")


class TextExtractor(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.parts: list[str] = []
        self.in_script = False
        self.in_style = False
        self.in_code = False

    def handle_starttag(self, tag, attrs):
        if tag in {"script", "style"}:
            self.in_script = tag == "script"
            self.in_style = tag == "style"
        if tag in {"h1", "h2", "h3", "h4", "h5", "h6", "p", "li", "tr", "pre", "br"}:
            self.parts.append("\n")
        if tag == "code":
            self.in_code = True

    def handle_endtag(self, tag):
        if tag == "script":
            self.in_script = False
        if tag == "style":
            self.in_style = False
        if tag == "code":
            self.in_code = False
        if tag in {"p", "li", "tr", "pre", "h1", "h2", "h3", "h4", "h5", "h6"}:
            self.parts.append("\n")

    def handle_data(self, data):
        if not self.in_script and not self.in_style:
            self.parts.append(data)


def fetch(url: str) -> str:
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "bale-claude-docs-updater/1.0"},
    )
    with urllib.request.urlopen(req, timeout=30) as response:
        raw = response.read()
        charset = response.headers.get_content_charset() or "utf-8"
        return raw.decode(charset, errors="replace")


def clean_text(raw: str) -> str:
    parser = TextExtractor()
    parser.feed(raw)
    text = html.unescape("".join(parser.parts))
    text = text.replace("\r", "")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n[ \t]+\n", "\n\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def write_snapshot(output: Path, source_url: str, raw_html: str):
    output.mkdir(parents=True, exist_ok=True)
    (output / "official.html").write_text(raw_html, encoding="utf-8")
    text = clean_text(raw_html)
    header = (
        "# Bale Official Documentation Snapshot\n\n"
        f"Source: {source_url}\n\n"
        "This file is generated by `tools/bale/update_docs.py`. "
        "Do not hand-edit it; edit project rules separately.\n\n---\n\n"
    )
    (output / "official.md").write_text(header + text + "\n", encoding="utf-8")

    # Preserve the compact, stable files but add a machine-readable freshness marker.
    (output / "_source.md").write_text(
        f"# Generated source\n\nURL: {source_url}\n\n"
        "Run `python tools/bale/update_docs.py` to refresh `official.html` and `official.md`.\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", default=DEFAULT_URL)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    try:
        raw = fetch(args.url)
    except Exception as exc:
        print(f"ERROR: could not fetch {args.url}: {exc}", file=sys.stderr)
        print("Tip: run this command on a machine with access to docs.bale.ai.", file=sys.stderr)
        return 2

    write_snapshot(args.output, args.url, raw)
    print(f"Updated Bale documentation in {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
