# Generated by Django 5.2.9 on 2026-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=200, verbose_name='Bot token')),
                ('bot_username', models.CharField(blank=True, max_length=100, verbose_name='Bot username')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bale settings',
                'verbose_name_plural': 'Bale settings',
            },
        ),
    ]
