# Generated by Django 5.2.9 on 2026-09-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0002_groupparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Round')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ready', 'Ready'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed'), ('walkover', 'Walkover'), ('retired', 'Retired'), ('default', 'Default')], default='scheduled', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.competition')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.group')),
                ('participant_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_participant_a', to='tournaments.participant')),
                ('participant_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_participant_b', to='tournaments.participant')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.stage')),
            ],
            options={
                'ordering': ['group', 'round_number', 'pk'],
                'indexes': [models.Index(fields=['group', 'round_number'], name='matches_mat_group_i_96763e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('participant_a', models.F('participant_b')), _negated=True), name='match_participants_distinct')],
            },
        ),
    ]
