# Generated by Django 5.2.9 on 2026-09-04 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('tournaments', '0002_groupparticipant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['group', 'round_number', 'bracket_slot', 'pk']},
        ),
        migrations.AddField(
            model_name='match',
            name='bracket_slot',
            field=models.IntegerField(blank=True, help_text='Position within the round, for knockout bracket rendering/progression. Unused for round robin.', null=True, verbose_name='Bracket slot'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_bye',
            field=models.BooleanField(default=False, verbose_name='BYE'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_third_place',
            field=models.BooleanField(default=False, verbose_name='Third place match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_participant_a', to='tournaments.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_participant_b', to='tournaments.participant'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['stage', 'round_number'], name='matches_mat_stage_i_7032f7_idx'),
        ),
    ]
