# Generated by Django 5.2.9 on 2026-09-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_options_match_bracket_slot_match_is_bye_and_more'),
        ('tournaments', '0002_groupparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField(verbose_name='Set number')),
                ('participant_a_score', models.PositiveSmallIntegerField(verbose_name='Score A')),
                ('participant_b_score', models.PositiveSmallIntegerField(verbose_name='Score B')),
            ],
            options={
                'ordering': ['match', 'set_number'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_won', to='tournaments.participant'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('winner__isnull', True), ('winner', models.F('participant_a')), ('winner', models.F('participant_b')), _connector='OR'), name='match_winner_is_a_participant'),
        ),
        migrations.AddField(
            model_name='matchset',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='matches.match'),
        ),
        migrations.AddConstraint(
            model_name='matchset',
            constraint=models.UniqueConstraint(fields=('match', 'set_number'), name='unique_set_number_per_match'),
        ),
    ]
