# Generated by Django 5.2.9 on 2026-09-05 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchset_match_winner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_refereed', to=settings.AUTH_USER_MODEL, verbose_name='Referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='scorekeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_scorekept', to=settings.AUTH_USER_MODEL, verbose_name='Scorekeeper'),
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start time'),
        ),
    ]
