# Generated by Django 5.2.9 on 2026-09-05 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_end_time_match_referee_match_scorekeeper_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('set_score_changed', 'Set score changed'), ('set_score_deleted', 'Set score deleted'), ('result_corrected', 'Result corrected')], max_length=30, verbose_name='Action')),
                ('set_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Set number')),
                ('previous_value', models.CharField(max_length=200, verbose_name='Previous value')),
                ('new_value', models.CharField(blank=True, max_length=200, verbose_name='New value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='matches.match')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Performed by')),
            ],
            options={
                'verbose_name': 'Match correction',
                'ordering': ['-created_at'],
            },
        ),
    ]
