# Generated by Django 5.2.9 on 2026-09-05 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_matchcorrection'),
        ('tournaments', '0004_competition_ranking_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='participant_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='matches_as_participant_a', to='tournaments.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='matches_as_participant_b', to='tournaments.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='matches_won', to='tournaments.participant'),
        ),
    ]
