# Generated by Django 5.2.9 on 2026-09-09 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_match_participant_a_alter_match_participant_b_and_more'),
        ('players', '0004_remove_player_unique_player_mobile_number_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='parent_tie',
            field=models.ForeignKey(blank=True, help_text="Set only on one of a team tie's individual-player sub-matches.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tie_sub_matches', to='matches.match', verbose_name='Tie'),
        ),
        migrations.AddField(
            model_name='match',
            name='tie_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Position in the tie's order of play (e.g. 1st of A vs X, B vs Y, C vs Z, A vs Y, B vs X).", null=True, verbose_name='Order within tie'),
        ),
        migrations.CreateModel(
            name='TieLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='players.player', verbose_name='Player A')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='players.player', verbose_name='Player B')),
                ('player_c', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='players.player', verbose_name='Player C')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tie_lineups', to='teams.team')),
                ('tie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='matches.match')),
            ],
            options={
                'verbose_name': 'Tie lineup',
                'constraints': [models.UniqueConstraint(fields=('tie', 'team'), name='unique_lineup_per_team_per_tie')],
            },
        ),
    ]
